[package]
name = "kea-infer"
version = "0.1.0"
edition = "2021"

[features]
default = []
whisper = ["dep:whisper-rs"]
sherpa = ["dep:sherpa-onnx"]

[dependencies]
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
serde_json.workspace = true
tempfile.workspace = true
sha2.workspace = true
bzip2 = "0.5"
tar = "0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dependencies.whisper-rs]
version = "0.13"
optional = true

[dependencies.sherpa-onnx]
version = "1.13.3"
optional = true
